module.exports={
  //登录
  login:"/manage/user/login.do",
  //退出登录
  loginOut:"/user/logout.do",
  //商品管理列表
  shopList:"/manage/product/list.do?",
  //查询
  switch:"/manage/product/search.do?listType=search&pageNum=1&",
  //上下架
  by:"/manage/product/set_sale_status.do?",
  //查看
  details:"/manage/product/detail.do?",
  //上传图片
  upload:"/manage/product/upload.do",
  //修改完成
Updata:"/manage/product/save.do?",
//品类管理
category:"/manage/category/get_category.do?categoryId=0"
}